name = "FractionalDiffEq"
uuid = "c7492dd8-6170-483b-af64-cefb6c377d9a"
authors = ["Qingyu Qu <erikqqy123@gmail.com>"]
version = "0.1.1"

[deps]
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MittagLeffler = "9c257583-4f8f-53fd-abd9-c69d5080dd54"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
InvertedIndices = "1.1"
MittagLeffler = "0.2"
SpecialFunctions = "0.7.0"
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
