name = "FractionalDiffEq"
uuid = "c7492dd8-6170-483b-af64-cefb6c377d9a"
authors = ["Qingyu Qu <erikqqy123@gmail.com>"]
version = "0.2.1"

[deps]
ApproxFun = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SpecialMatrices = "928aab9d-ef52-54ac-8ca1-acd7ca42c160"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
ApproxFun = "0.13"
FFTW = "1.0.0"
InvertedIndices = "1.1"
Polynomials = "2.0.24, 3"
QuadGK = "2"
SpecialFunctions = "0.7, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 0.14"
SpecialMatrices = "2.0.0"
UnPack = "1.0.0"
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
